twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes:
        - bootstrap_4_layout.html.twig
    globals:
        locale: "%locale%"
        version: "%version%"
        title: "%title%"
