Novosga\Entity\EntityMetadata:
    type: mappedSuperclass
    id:
        namespace:
            type: string
            length: 30
            id: true
        name:
            type: string
            length: 30
            id: true
    fields:
        value:
            type: json
            nullable: false
