Novosga\Entity\PainelSenha:
    type: entity
    table: painel_senha
    id:
        id:
            type: integer
            generator:
                strategy: IDENTITY
    fields:
        numeroSenha:
            type: integer
            unique: false
            nullable: false
            column: num_senha
        siglaSenha:
            type: string
            length: 3
            unique: false
            nullable: false
            column: sig_senha
        mensagem:
            type: string
            length: 255
            unique: false
            nullable: false
            column: msg_senha
        local:
            type: string
            length: 15
            unique: false
            nullable: false
        numeroLocal:
            type: smallint
            unique: false
            nullable: false
            column: num_local
        peso:
            type: smallint
            unique: false
            nullable: false
        prioridade:
            type: string
            length: 100
            unique: false
            nullable: true
        nomeCliente:
            type: string
            length: 100
            unique: false
            nullable: true
            column: nome_cliente
        documentoCliente:
            type: string
            length: 30
            unique: false
            nullable: true
            column: documento_cliente
    manyToOne:
        servico:
            targetEntity: Novosga\Entity\Servico
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                servico_id:
                    referencedColumnName: id
            orphanRemoval: false
        unidade:
            targetEntity: Novosga\Entity\Unidade
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                unidade_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
